apiVersion: apps/v1
kind: Deployment
metadata:
  name: daniel
spec:
  selector:
    matchLabels:
      app: daniel
  replicas: 2
  template:
    metadata:
      labels:
        app: daniel
    spec:
      containers:
        - name: daniel
          image: idock.daumkakao.io/ssd-intern/daniel
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: daniel
  labels:
    app: daniel
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: daniel
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mynoti-daniel
spec:
  rules:
    - host: mynoti-daniel.ing.ssd-intern.k8s.9rum.cc
      http:
        paths:
          - path: /
            backend:
              serviceName: mynoti-daniel
              servicePort: 8080